dist: trusty
sudo: required

language: csharp
solution: $solution_name

addons:
  sonarcloud:
    organization: $sonar_organization_name
    token: $sonar_token

install:
  - nuget restore PESEL.sln

script:
  - msbuild /p:Configuration=Release $solution_name
  - sonar-scanner -Dsonar.verbose=true -X  

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - $my_mail
    on_success: always # default: change
    on_failure: always # default: always
