dist: trusty
sudo: required

language: csharp
solution: PESEL.sln

install:
  - nuget restore PESEL.sln

script:
  - msbuild /p:Configuration=Release PESEL.sln

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - $my_mail
    on_success: always # default: change
    on_failure: always # default: always
