dist: trusty
sudo: required

language: csharp
solution: PESEL.sln

addons:
  sonarcloud:
    organization: "asienicki-github"
    token: $sonar_token

install:
  - nuget restore PESEL.sln

script:
  - msbuild /p:Configuration=Release PESEL.sln
  - sonar-scanner -Dsonar.verbose=true -X 

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - $my_mail
    on_success: always # default: change
    on_failure: always # default: always
